package com.crypto_trader.scheduler.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/proto/DataModel.proto
// Protobuf Java Version: 4.28.1

public final class DataModel {
  private DataModel() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      DataModel.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PCandleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PCandle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double open = 1;</code>
     * @return The open.
     */
    double getOpen();

    /**
     * <code>double close = 2;</code>
     * @return The close.
     */
    double getClose();

    /**
     * <code>double high = 3;</code>
     * @return The high.
     */
    double getHigh();

    /**
     * <code>double low = 4;</code>
     * @return The low.
     */
    double getLow();

    /**
     * <code>double volume = 5;</code>
     * @return The volume.
     */
    double getVolume();

    /**
     * <code>string time = 6;</code>
     * @return The time.
     */
    java.lang.String getTime();
    /**
     * <code>string time = 6;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();
  }
  /**
   * Protobuf type {@code PCandle}
   */
  public static final class PCandle extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PCandle)
      PCandleOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        PCandle.class.getName());
    }
    // Use PCandle.newBuilder() to construct.
    private PCandle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    public PCandle() {
      time_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataModel.internal_static_PCandle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataModel.internal_static_PCandle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataModel.PCandle.class, DataModel.PCandle.Builder.class);
    }

    public static final int OPEN_FIELD_NUMBER = 1;
    private double open_ = 0D;
    /**
     * <code>double open = 1;</code>
     * @return The open.
     */
    @java.lang.Override
    public double getOpen() {
      return open_;
    }

    public static final int CLOSE_FIELD_NUMBER = 2;
    private double close_ = 0D;
    /**
     * <code>double close = 2;</code>
     * @return The close.
     */
    @java.lang.Override
    public double getClose() {
      return close_;
    }

    public static final int HIGH_FIELD_NUMBER = 3;
    private double high_ = 0D;
    /**
     * <code>double high = 3;</code>
     * @return The high.
     */
    @java.lang.Override
    public double getHigh() {
      return high_;
    }

    public static final int LOW_FIELD_NUMBER = 4;
    private double low_ = 0D;
    /**
     * <code>double low = 4;</code>
     * @return The low.
     */
    @java.lang.Override
    public double getLow() {
      return low_;
    }

    public static final int VOLUME_FIELD_NUMBER = 5;
    private double volume_ = 0D;
    /**
     * <code>double volume = 5;</code>
     * @return The volume.
     */
    @java.lang.Override
    public double getVolume() {
      return volume_;
    }

    public static final int TIME_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object time_ = "";
    /**
     * <code>string time = 6;</code>
     * @return The time.
     */
    @java.lang.Override
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <code>string time = 6;</code>
     * @return The bytes for time.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(open_) != 0) {
        output.writeDouble(1, open_);
      }
      if (java.lang.Double.doubleToRawLongBits(close_) != 0) {
        output.writeDouble(2, close_);
      }
      if (java.lang.Double.doubleToRawLongBits(high_) != 0) {
        output.writeDouble(3, high_);
      }
      if (java.lang.Double.doubleToRawLongBits(low_) != 0) {
        output.writeDouble(4, low_);
      }
      if (java.lang.Double.doubleToRawLongBits(volume_) != 0) {
        output.writeDouble(5, volume_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, time_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(open_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, open_);
      }
      if (java.lang.Double.doubleToRawLongBits(close_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, close_);
      }
      if (java.lang.Double.doubleToRawLongBits(high_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, high_);
      }
      if (java.lang.Double.doubleToRawLongBits(low_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, low_);
      }
      if (java.lang.Double.doubleToRawLongBits(volume_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, volume_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataModel.PCandle)) {
        return super.equals(obj);
      }
      DataModel.PCandle other = (DataModel.PCandle) obj;

      if (java.lang.Double.doubleToLongBits(getOpen())
          != java.lang.Double.doubleToLongBits(
              other.getOpen())) return false;
      if (java.lang.Double.doubleToLongBits(getClose())
          != java.lang.Double.doubleToLongBits(
              other.getClose())) return false;
      if (java.lang.Double.doubleToLongBits(getHigh())
          != java.lang.Double.doubleToLongBits(
              other.getHigh())) return false;
      if (java.lang.Double.doubleToLongBits(getLow())
          != java.lang.Double.doubleToLongBits(
              other.getLow())) return false;
      if (java.lang.Double.doubleToLongBits(getVolume())
          != java.lang.Double.doubleToLongBits(
              other.getVolume())) return false;
      if (!getTime()
          .equals(other.getTime())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOpen()));
      hash = (37 * hash) + CLOSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getClose()));
      hash = (37 * hash) + HIGH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHigh()));
      hash = (37 * hash) + LOW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLow()));
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVolume()));
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataModel.PCandle parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataModel.PCandle parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataModel.PCandle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataModel.PCandle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataModel.PCandle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataModel.PCandle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataModel.PCandle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static DataModel.PCandle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static DataModel.PCandle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static DataModel.PCandle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataModel.PCandle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static DataModel.PCandle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataModel.PCandle prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PCandle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PCandle)
        DataModel.PCandleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataModel.internal_static_PCandle_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataModel.internal_static_PCandle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataModel.PCandle.class, DataModel.PCandle.Builder.class);
      }

      // Construct using DataModel.PCandle.newBuilder()
      public Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        open_ = 0D;
        close_ = 0D;
        high_ = 0D;
        low_ = 0D;
        volume_ = 0D;
        time_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataModel.internal_static_PCandle_descriptor;
      }

      @java.lang.Override
      public DataModel.PCandle getDefaultInstanceForType() {
        return DataModel.PCandle.getDefaultInstance();
      }

      @java.lang.Override
      public DataModel.PCandle build() {
        DataModel.PCandle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DataModel.PCandle buildPartial() {
        DataModel.PCandle result = new DataModel.PCandle(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(DataModel.PCandle result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.open_ = open_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.close_ = close_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.high_ = high_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.low_ = low_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.volume_ = volume_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.time_ = time_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataModel.PCandle) {
          return mergeFrom((DataModel.PCandle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataModel.PCandle other) {
        if (other == DataModel.PCandle.getDefaultInstance()) return this;
        if (other.getOpen() != 0D) {
          setOpen(other.getOpen());
        }
        if (other.getClose() != 0D) {
          setClose(other.getClose());
        }
        if (other.getHigh() != 0D) {
          setHigh(other.getHigh());
        }
        if (other.getLow() != 0D) {
          setLow(other.getLow());
        }
        if (other.getVolume() != 0D) {
          setVolume(other.getVolume());
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                open_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                close_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                high_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                low_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                volume_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 50: {
                time_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double open_ ;
      /**
       * <code>double open = 1;</code>
       * @return The open.
       */
      @java.lang.Override
      public double getOpen() {
        return open_;
      }
      /**
       * <code>double open = 1;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(double value) {

        open_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double open = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000001);
        open_ = 0D;
        onChanged();
        return this;
      }

      private double close_ ;
      /**
       * <code>double close = 2;</code>
       * @return The close.
       */
      @java.lang.Override
      public double getClose() {
        return close_;
      }
      /**
       * <code>double close = 2;</code>
       * @param value The close to set.
       * @return This builder for chaining.
       */
      public Builder setClose(double value) {

        close_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double close = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClose() {
        bitField0_ = (bitField0_ & ~0x00000002);
        close_ = 0D;
        onChanged();
        return this;
      }

      private double high_ ;
      /**
       * <code>double high = 3;</code>
       * @return The high.
       */
      @java.lang.Override
      public double getHigh() {
        return high_;
      }
      /**
       * <code>double high = 3;</code>
       * @param value The high to set.
       * @return This builder for chaining.
       */
      public Builder setHigh(double value) {

        high_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double high = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000004);
        high_ = 0D;
        onChanged();
        return this;
      }

      private double low_ ;
      /**
       * <code>double low = 4;</code>
       * @return The low.
       */
      @java.lang.Override
      public double getLow() {
        return low_;
      }
      /**
       * <code>double low = 4;</code>
       * @param value The low to set.
       * @return This builder for chaining.
       */
      public Builder setLow(double value) {

        low_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double low = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000008);
        low_ = 0D;
        onChanged();
        return this;
      }

      private double volume_ ;
      /**
       * <code>double volume = 5;</code>
       * @return The volume.
       */
      @java.lang.Override
      public double getVolume() {
        return volume_;
      }
      /**
       * <code>double volume = 5;</code>
       * @param value The volume to set.
       * @return This builder for chaining.
       */
      public Builder setVolume(double value) {

        volume_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double volume = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000010);
        volume_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>string time = 6;</code>
       * @return The time.
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string time = 6;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string time = 6;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        time_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string time = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        time_ = getDefaultInstance().getTime();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string time = 6;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        time_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PCandle)
    }

    // @@protoc_insertion_point(class_scope:PCandle)
    private static final DataModel.PCandle DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataModel.PCandle();
    }

    public static DataModel.PCandle getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PCandle>
        PARSER = new com.google.protobuf.AbstractParser<PCandle>() {
      @java.lang.Override
      public PCandle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PCandle> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PCandle> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DataModel.PCandle getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PCandle_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PCandle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/resources/proto/DataModel.pro" +
      "to\"_\n\007PCandle\022\014\n\004open\030\001 \001(\001\022\r\n\005close\030\002 \001" +
      "(\001\022\014\n\004high\030\003 \001(\001\022\013\n\003low\030\004 \001(\001\022\016\n\006volume\030" +
      "\005 \001(\001\022\014\n\004time\030\006 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PCandle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PCandle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PCandle_descriptor,
        new java.lang.String[] { "Open", "Close", "High", "Low", "Volume", "Time", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
